import express from "express";
import { createUser, login, logout } from "../controllers/UserController.js";
import { verifyToken } from "../middleware/VerifyToken.js";
import { refreshToken } from "../controllers/TokenController.js";
const router = express.Router();
router.post("/login", login);
router.post("/register", createUser);
router.get("/logout", verifyToken, logout);
router.get("/refresh", refreshToken);
export default router;
