import swaggerAutogen from "swagger-autogen";

const doc = {
  info: {
    version: "1.0.0",
    title: "Todolist WEB API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module. Swagger documentation for Todolist Web develope by Ahmad Alif Sofian",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
};

const outputFile = "./swagger-output.json";
const endpointsFiles = [
  "./routers/TodolistRouter.js",
  "./routers/UserRouter.js",
];

swaggerAutogen()(outputFile, endpointsFiles, doc).then(async () => {
  await import("./index.js");
});
